### ISSUE TITLE
Ukol6

### ISSUE THREAD

**Issue by pupikovam** [pupikovam/Python_Czechitas_2022#6]
řešení zde: https://github.com/pupikovam/Python_Czechitas_2022/commit/9fa45805cc470efff6258b2a57675f0a38a0629c

mám ještě dotaz: v řešení jsem použila obrácený zápis pro cyklus for. Nicméně, původně jsem zkoušela klasicky a docela jsem se na tom zasekla.

chtěla jsem použít následovně:
for auto in auta:
    auto=auto.replace(",", ".")
    auto=auto.split()
oproti v úkolu požitému:
auta=[auto.replace(",", ".") for auto in auta]
auta=[auto.split() for auto in auta]

narazila jsem ale na to, že se mi to v tom případě sice přepíše na úrovni auto, ale pak už to tak nezůstává v proměnné auta. Jak bych to měla zapsat, aby se mi přepsalo a já s tím mohla pracovat jako v kódu, jak jsem použila v úkolu? Já totiž původně myslela, že se mi to pak přepíše i v proměnné auta. Nebo bych musela vytvořit jinou proměnnou, kam bych pak přidávala metodou append či něco podobného? No - snad se to z mého popisu dá pochopit, co myslím....

**Comment by AnetaPopelova** [comment]
Myslim, ze rozumim.

Pokud chces pomoci "normalniho" for cyklu menit zaznamy, musis je pak znovu ulozit do nejakeho seznamu pomoci `.append`.  Najak tahle:

```
auta2 = []
for auto in auta:
    auto = auto.replace(",", ".")
    auto = auto.split()
    auta2.append(auto)
```
